#!/bin/bash

# List of config files
CONFIG_FILES=(
  "FR1/config.txt"
  "FR2/config.txt"
  "FR3/config.txt"
  "FR4/config.txt"
  "FR5/config.txt"
  "FR6/config.txt"
  "FR7/config.txt"
  "FR8/config.txt"
  "FR9/config.txt"
  "FR10/config.txt"
  "FR10/config.txt"
  "FR12/config.txt"
  "FR13/config.txt"
  "FR14/config.txt"
  "FR15/config.txt"
  "FR16/config.txt"
  "FR17/config.txt"
  "FR18/config.txt"
  "FR19/config.txt"
  "FR20/config.txt"
  "FR21/config.txt"
  "FR22/config.txt"
  "FR23/config.txt"
  "FR24/config.txt"
  "FR25/config.txt"
  "FR26/config.txt"
  "FR27/config.txt"
  "FR28/config.txt"
  "FR29/config.txt"
  "FR30/config.txt"
  "FR31/config.txt"
  "FR32/config.txt"
  "FR33/config.txt"
  "FR34/config.txt"
  "FR35/config.txt"
  "FR36/config.txt"
  "FR37/config.txt"
  "FR38/config.txt"
  "FR39/config.txt"
  "FR40/config.txt"
  "FR41/config.txt"
  "FR42/config.txt"
  "FR43/config.txt"
  "FR44/config.txt"
  "FR45/config.txt"
  "FR46/config.txt"
  "FR47/config.txt"
  "FR48/config.txt"
  "FR49/config.txt"
  "FR50/config.txt"
  "FR51/config.txt"
  "FR52/config.txt"
  "FR53/config.txt"
  "FR54/config.txt"
  "FR55/config.txt"
  "FR56/config.txt"
  "FR57/config.txt"
  "FR58/config.txt"
  "FR59/config.txt"
  "FR60/config.txt"
  "FR61/config.txt"
  "FR62/config.txt"
  "FR63/config.txt"
  "FR64/config.txt"
  "FR65/config.txt"
  "FR66/config.txt"
  "FR67/config.txt"
  "FR68/config.txt"
)

# Run NOVOPlasty for each config file
for CONFIG in "${CONFIG_FILES[@]}"; do
  echo "Running NOVOPlasty for $CONFIG..."
  NOVOPlasty4.3.5.pl -c "$CONFIG"
  if [ $? -ne 0 ]; then
    echo "Error running NOVOPlasty for $CONFIG. Exiting."
    exit 1
  fi
  echo "Completed $CONFIG"
done

echo "All configurations processed successfully!"
